### PR TITLE
Add support to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by erikson84**

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks @erikson84 for the PR, I removed non-ASCII characters to avoid R CMD warnings, I think it's good now.

**Comment by bthieurmel** [comment]
Hi @erikson84 and thanks for your PR. 

Can you confirm or not that in fact this is more globally a ``Portuguese`` support or there is a some *strong* diffrence between ``Portuguese`` and ``Brazilian portuguese`` ?

**Comment by erikson84** [comment]
@bthieurmel , most software packages distinguish between brazilian portuguese and portuguese. On the other hand, I believe a non-brazilian portuguese speaker would have no problem understanding the text.

**Comment by bthieurmel** [comment]
Ok. Some keep ``br``. Now merge on master, and on CRAN soon.

Thanks

**Pull request merged**
