### PR TITLE
Way to disable users db and logs download

### PR DESCRIPTION
**Pull request by StatisMike**
Adressing issue #110. Adds `download` argument to `secure_app` function, which defaults to `c("users", "logs")`, allowing the respective downloads from **admin panel**. To disable both, you can set `download = NULL`. 

Also, minor typo mistake correction in polish labels.

### CODE REVIEW

**Comment by StatisMike** [comment]
Need another implementation for additional security (not only not showing the `downloadButtons`, but also disabling `downloadHandlers`)

**Comment by StatisMike** [comment]
Option to download `db` and `logs` depends on `options("shinymanager.download")` value that defaults to `c("db", "logs")`. To disable both specify `options("shinymanager.download" = "")`

**Comment by StatisMike** [comment]
@bthieurmel Can I request a review and - if everything is ok - pull?

**Comment by bthieurmel** [comment]
Hi @StatisMike : Can I check / review your pull request and merge if ok ?

**Comment by StatisMike** [comment]
@bthieurmel Certainly!

**Comment by StatisMike** [comment]
@f-leborgne AFAIK the pull request wasn't accepted yet. Even if this will get accepted, you will need to download development version from GitHub, I presume

**Pull request merged**
